[package]
name = "oxid-trainer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "train"
path = "src/main.rs"

[[bin]]
name = "convert"
path = "src/bin/convert.rs"

[[bin]]
name = "preprocess"
path = "src/bin/preprocess.rs"

[features]
default = []
metal = ["bullet/metal"]
cuda = ["bullet/cuda"]

[dependencies]
bullet = { git = "https://github.com/jw1912/bullet", rev = "cebc78a0", package = "bullet_lib", default-features = false }
bullet_trainer = { git = "https://github.com/jw1912/bullet", rev = "cebc78a0", package = "bullet-trainer" }
